---
- name: Update apt cache and upgrade system packages
  apt:
    update_cache: true
    upgrade: dist

- name: Install baseline system utilities
  apt:
    name:
      - curl
      - open-iscsi
      - nfs-common
    state: present

  # --- Memory Safety for AWS Free Tier ---
- name: Check if swapfile exists
  stat:
    path: /swapfile
  register: swapfile_stat

- name: Create 2GB swapfile
  command: fallocate -l 2G /swapfile
  when: not swapfile_stat.stat.exists

- name: Set permissions on swapfile
  file:
    path: /swapfile
    owner: root
    group: root
    mode: '0600'
  when: not swapfile_stat.stat.exists

- name: Format swapfile
  command: mkswap /swapfile
  when: not swapfile_stat.stat.exists

- name: Enable swapfile
  command: swapon /swapfile
  when: not swapfile_stat.stat.exists

- name: Ensure swap is mounted in /etc/fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present