apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manual-flask
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/SagarGi/gitops-k3s-aws.git'
    targetRevision: HEAD
    path: helm/app-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true